name: pro-mvn/plan-mvn
permissions:
  checks: write
  pull-requests: write
on:
 push:
  branches: master
 pull_request:
  branches: master
#   # The shortest interval you can run scheduled workflows is once every 5 minutes.
#   period: '180'
jobs:
  Default-Stage-DEVE1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        clean: false
    - uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '11'
    - name: Run Maven
      run: mvn package
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
         test-results/**/*.xml
         test-results/**/*.trx
         test-results/**/*.json
